---
title: "Lab 11 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
```

## Seating & Set-up
1. Please make sure that you sit next to your group members for the rest of the quarter.
2. Please set-up your computer as normal.

## Warm-up
For this warm-up, please use the `heartrate` data. Be sure to label your plots!
```{r}
library(tidyverse)
library(janitor)
```

```{r}
heartrate <- read_csv("data/heartrate.csv")
heartrate <- clean_names(heartrate)
heartrate_long <- heartrate %>% 
  pivot_longer(-patient, 
               names_to = "drug",
               values_to = "heartrate")
```

1. Make a plot that compares the heartrate of patients for drug a.
```{r}
heartrate_long %>% 
  filter(drug == "a") %>% 
  ggplot(aes(x=patient, y=heartrate, fill = patient))+
  geom_col()+
  labs(title = "Heartrate of Patients for Drug a",
       x = "Patient",
       y= "Heartrate")+
  theme(plot.title = element_text(size = rel(1), hjust = 0.5))
```

2. Make a plot that compares heartrate (as a range) for each drug.
```{r}
heartrate_long %>% 
  ggplot(aes(x=drug, y=heartrate, fill = drug))+
  geom_boxplot(alpha = 0.7)+
  labs(title = "Heartrate of Patients for All Drugs",
       x = "Drug",
       y= "Heartrate")+
  theme(plot.title = element_text(size = rel(1.2), hjust = 0.5))
```

